<template>
  <el-form>
    <el-row :gutter="20">
      <el-col :span="10">
        <el-form-item>
          <h3>输入 JSON 字符串</h3>
          <el-input v-model="textarea1" :autosize="{ minRows: 12, maxRows: 30 }" type="textarea"
            placeholder="请输入 JSON 字符串" />
        </el-form-item>
        <el-form-item style="text-align: center;">
          <el-button type="primary" size="large" @click="modify">转换</el-button>
        </el-form-item>
      </el-col>
      <el-col :span="14">
        <el-form-item>
         
          <div style="border: 1px solid #dcdfe6; padding: 10px; border-radius: 4px; background-color: #f5f7fa;">
            <pre>{{ textarea2 }}</pre>
          </div>
        </el-form-item>
      </el-col>
    </el-row>
    <el-row :gutter="20">
      <el-col :span="12">
        <el-form-item>
         
          <div style="border: 1px solid #dcdfe6; padding: 10px; border-radius: 4px; background-color: #f5f7fa;">
            <pre>{{ goStruct }}</pre>
          </div>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item>
          
          <div style="border: 1px solid #dcdfe6; padding: 10px; border-radius: 4px; background-color: #f5f7fa;">
            <pre>{{ javaClass }}</pre>
          </div>
        </el-form-item>
      </el-col>
    </el-row>
  </el-form>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { ElMessage } from 'element-plus';

export default defineComponent({
  name: "JsonFormatter",
  setup() {
    const textarea1 = ref('');
    const textarea2 = ref('');
    const goStruct = ref('');
    const javaClass = ref('');

    const isValidJson = (str: string) => {
      try {
        JSON.parse(str);
        return true;
      } catch (e) {
        return false;
      }
    };

    const formatJson = (str: string) => {
      return JSON.stringify(JSON.parse(str), null, 2);
    };

    const jsonToGoStruct = (json: string): string => {
      try {
        const obj = JSON.parse(json);
        let result = 'type AutoGenerated struct {\n';
        for (const key in obj) {
          result += `  ${key.charAt(0).toUpperCase() + key.slice(1)} ${typeof obj[key] === 'number' ? 'int' : 'string'} \`json:"${key}"\`\n`;
        }
        result += '}';
        return result;
      } catch {
        return '无法生成 Go 结构体';
      }
    };

    const jsonToJavaClass = (json: string): string => {
      try {
        const obj = JSON.parse(json);
        let result = 'public class AutoGenerated {\n';
        for (const key in obj) {
          result += `  private ${typeof obj[key] === 'number' ? 'int' : 'String'} ${key};\n`;
        }
        result += '}';
        return result;
      } catch {
        return '无法生成 Java 类';
      }
    };

    const modify = () => {
      if (textarea1.value === "") {
        ElMessage.info("请填写要转换的内容！");
        return;
      }

      if (!isValidJson(textarea1.value)) {
        ElMessage.error("输入的字符串不是有效的 JSON 格式！");
        return;
      }

      textarea2.value = formatJson(textarea1.value);
      goStruct.value = jsonToGoStruct(textarea1.value);
      javaClass.value = jsonToJavaClass(textarea1.value);
      ElMessage.success("转换完成！");
    };

    return {
      textarea1,
      textarea2,
      goStruct,
      javaClass,
      modify,
    };
  },
});
</script>

<style scoped></style>
